kind: pipeline
type: exec
name: StarloneAuthProxy

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - docker build -t starlineauthproxy .;

- name: delete old containers
  failure: ignore
  commands:
  - docker stop starlineauthproxy;
  - docker rm starlineauthproxy;

- name: publish
  commands:
  - docker run -d --restart=no -m=350m --memory-swap=350m --cpus=".5" --pids-limit=200 -p 5005:5000 --name starlineauthproxy starlineauthproxy;
